### ISSUE TITLE
EF Concerns

### ISSUE THREAD

**Issue by ErikEJ** [tjaybelt/SQL#1]
Happy to comment on your document, but please make it a markdown document so it is possible.

Agree with many of your concerns, but do not agree with all of them, and some of them could be contested imho.

**Comment by tjaybelt** [comment]
> Happy to comment on your document, but please make it a markdown document so it is possible.
> 
> Agree with many of your concerns, but do not agree with all of them, and some of them could be contested imho.

will do!!

**Comment by tjaybelt** [comment]
here ya go
https://github.com/tjaybelt/SQL/blob/main/SQL%20Standards.md

**Comment by ErikEJ** [comment]
Looks good  - do not see any EF Concerns in that doc though

**Comment by tjaybelt** [comment]
thanks!!



TJay Belt



 Data ArchitectFriend of Red Gate Regional Mentor SQLPASSLinkedIn https://www.linkedin.com/in/tjaybeltBlog       https://tjaybelt.blogspot.comTwitter:  @TJayBelt

 


 

    On Wednesday, February 23, 2022, 12:37:37 AM MST, Erik Ejlskov Jensen ***@***.***> wrote:  
 
 


Looks good - do not see any EF Concerns in that doc though

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tjaybelt** [comment]
MD made, and reviewed
